if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
  set(TD_WINDOWS ON)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
  set(TD_MACOS ON)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
  set(TD_LINUX ON)
endif()

function(build_dashboard_resource RES_FILE RES_NAME)
  set(RES_OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/res/${RES_NAME}.h")
  file(REMOVE ${RES_OUTPUT})
  file(READ ${RES_FILE} filedata HEX)
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," filedata ${filedata})
  file(APPEND ${RES_OUTPUT} "unsigned char ${RES_NAME}[] = {${filedata}};\nconst unsigned ${RES_NAME}_size = sizeof(${RES_NAME});\n")
endfunction()